### PR TITLE
Mount support & character change fix

### PR DESCRIPTION
**Pull request by incedius**
Right click on mount in dressing room to change appearance of mount client side.

Known Issues:
If original mount is flying and the applied mount is ground, can't dismount.

Flying mounts should be applied to flying mounts.
Ground mounts should be applied to ground mounts.

### CODE REVIEW

**Comment by TeraProxy** [comment]
Interesting. Let me look into this.

**Comment by TeraProxy** [comment]
Nice work! I'll think of a way to integrate it properly and try to find a workaround for the dismount bug. You'll be credited of course.

**Comment by TeraProxy** [comment]
I just pushed a new version which includes custom mount support and fixes the issue you found when switching characters. Thanks a lot again! You'll stay credited in the code and readme.

**Comment by incedius** [comment]
Glad to help!

**Pull request closed without merging**
